# Generated by Django 2.1.7 on 2019-03-18 07:45

from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status_content', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('soldout', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=market.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Base')),
                ('edition', models.CharField(max_length=5)),
                ('author', models.CharField(max_length=10)),
            ],
            bases=('market.base',),
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Comment')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Book')),
            ],
            bases=('market.comment',),
        ),
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('images_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Images')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Book')),
            ],
            bases=('market.images',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Base')),
            ],
            bases=('market.base',),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Comment')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Product')),
            ],
            bases=('market.comment',),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('images_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Images')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Product')),
            ],
            bases=('market.images',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Base')),
                ('position', models.CharField(max_length=100)),
            ],
            bases=('market.base',),
        ),
        migrations.CreateModel(
            name='RoomComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Comment')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Room')),
            ],
            bases=('market.comment',),
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('images_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Images')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Room')),
            ],
            bases=('market.images',),
        ),
        migrations.AddField(
            model_name='comment',
            name='recomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Comment'),
        ),
    ]
