# Generated by Django 2.1.7 on 2019-04-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_product_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
