# Generated by Django 2.1.7 on 2019-04-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20190411_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
