# Generated by Django 2.1.7 on 2019-04-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20190412_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_hit',
        ),
        migrations.AddField(
            model_name='base',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
