# Generated by Django 2.1.7 on 2019-04-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20190412_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimages',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookimages',
            name='images_ptr',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='images_ptr',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='roomimages',
            name='images_ptr',
        ),
        migrations.RemoveField(
            model_name='roomimages',
            name='room',
        ),
        migrations.DeleteModel(
            name='BookImages',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.DeleteModel(
            name='RoomImages',
        ),
    ]
