# Generated by Django 2.1.7 on 2019-05-11 17:49

from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20190412_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=market.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('images_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Images')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Book')),
            ],
            bases=('market.images',),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('images_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Images')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Product')),
            ],
            bases=('market.images',),
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('images_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Images')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Room')),
            ],
            bases=('market.images',),
        ),
    ]
